services:
  apache:
    build: .  #lance le dockerfile dans le repertoire courant
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: JCYYh5JWi6JwIWq5
      MYSQL_DATABASE: camagru_db
      MYSQL_USER: camagru_user
      MYSQL_PASSWORD: vDieYHfb70cjHl8U
    volumes:
      - db_data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql  #bind mount

volumes:
  db_data:

